# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the Prisma CLI globally
RUN npm install prisma@3 -g

# Copy the entire project to the container
COPY . .

# Run the Prisma migration command
CMD ["prisma", "migrate", "dev", "--preview-feature"]
