version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: trustblock
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
