# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Expose the port on which the NestJS application runs
EXPOSE 3000

# Start the NestJS application
CMD ["sh", "-c", "npm run seed && npm run start:prod"]
